// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PigeonLatLon;

@interface PigeonLatLon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLat:(NSNumber *)lat
    lon:(NSNumber *)lon;
@property(nonatomic, strong) NSNumber * lat;
@property(nonatomic, strong) NSNumber * lon;
@end

/// The codec used by MapsPlatformToFlutterApi.
NSObject<FlutterMessageCodec> *MapsPlatformToFlutterApiGetCodec(void);

@interface MapsPlatformToFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)updateLocationMapId:(NSNumber *)mapId latLon:(PigeonLatLon *)latLon completion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by MapsFlutterToPlatformApi.
NSObject<FlutterMessageCodec> *MapsFlutterToPlatformApiGetCodec(void);

@protocol MapsFlutterToPlatformApi
- (void)moveMapWithId:(NSNumber *)mapId to:(PigeonLatLon *)latLon completion:(void(^)(FlutterError *_Nullable))completion;
- (void)causeErrorOnMapWithId:(NSNumber *)mapId completion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void MapsFlutterToPlatformApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MapsFlutterToPlatformApi> *_Nullable api);

NS_ASSUME_NONNULL_END
